### ISSUE TITLE
yaml config_file not working

### ISSUE THREAD

**Issue by DragonZ** [timotheus/ebaysdk-python#131]
Here is my code following the tutorial:
from ebaysdk.trading import Connection as Trading
from ebaysdk.exception import ConnectionError

try:    
    api = Trading(config_file='EBAY_YAML')
    response = api.execute('GetUser', {})
    print(response.dict())
    print(response.reply)
except ConnectionError as e:
    print(e)
    print(e.response.dict())

Here is my config file in the same directory:
name: ebay_api_config

\# Trading API Sandbox - https://www.x.com/developers/ebay/products/trading-api
api.sandbox.ebay.com:
    compatability: 837
    appid: my appid
    certid: my certificate id
    devid: my devid
    token: sandbox user token

However, it seems that the program never tried to read the config file. It keep giving the following error:
u'GetUser: Class: RequestError, Severity: Error, Code: 127, Application name invalid. API application "None" invalid.'

It never read my appid. However, if I hard code all ids into my code instead of using config_file. Everything works fine. Any ideas?

Thanks

**Comment by jmtoung** [comment]
Also getting this error. Any fixes?

**Comment by timotheus** [comment]
Strange, not sure what the issue is. I've never heard of or ran into this issue. The config library is pretty simple. Can you enable some of the debug statements and help me isolate where it's failing.

https://github.com/timotheus/ebaysdk-python/blob/master/ebaysdk/config.py

I assume it's finding your config file, otherwise it would throw an exception.

**Comment by jmtoung** [comment]
hi @timotheus, 

I figured out my error, apologies. I copied your quick example from the home page of the git repository, and switched out ebaysdk.finding to ebaysdk.trading, without realizing that in the Connection() instantiation for trading, you need to specify the domain. After specifying the appropriate domain, I fixed the error. Thanks.

**Comment by timotheus** [comment]
Cool. Glad it's working for you.

**Comment by bartekmalysz** [comment]
Hi there,

I ran into similar problem as @jmtoung, however changing the endpoint did not help.
I tried these https://developer.ebay.com/devzone/guides/ebayfeatures/Basics/Call-RoutingRequest.html#ServiceEndpoints, but still fails to establish connection:

ConnectionError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //api.sandbox.ebay.com/ws/api.dll/ws/api.dll (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001E4141076D8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

Would you please point me into the right direction.

P.S. @timotheus many thanks for the sdk!
